### ISSUE TITLE
Configurar y crear en DO todo lo necesario:

### ISSUE THREAD

**Issue by yodra** [fullstacktf/ControlHorarios-Backend#3]
- [x] Crear un droplet
- [x] Instalar Docker
- [x] Configuración Cloudflare para HTTPS y gestionar DNS
- [x] Configuración Nginx/Apache como servidor
